### ISSUE TITLE
Encountering error when using ContractPromise for ink! 4.0.0-beta Aleph Zero Testnet

### ISSUE THREAD

**Issue by SnoopieWeb3** [Cardinal-Cryptography/ink4-migration#5]
I am facing this error when using new ContractPromise.

The log in console is:

```bash
Error: Your runtime does not expose the api.call.contractsApi.call runtime interfaces
```

Are there any pointers to fixes?

**Comment by deuszx** [comment]
Hey @EdinyangaOttoho , which chain are you trying to connect with? What are the lib verions you're using?

**Comment by SnoopieWeb3** [comment]
I have resolved the issue. Thanks. I was trying to connect to Aleph Zero
Testnet (ink4.0.0-beta compatible)

**Comment by deuszx** [comment]
Can you close the issue if you think it's no longer necessary?
